---
- name: Attempting to generate temporary file
  tags: dome9
  tempfile:
    prefix: dome9.
    state: file
    suffix: .rpm
  register: dome9_tempfile

- name: Attempting to download package to temporary location
  tags: dome9
  get_url:
    dest: "{{ dome9_tempfile.path }}"
    force: yes
    url: "{{ dome9_fetch }}"
  register: dome9_get_url
  when: dome9_tempfile is success

- name: Ensure that the {{ dome9_pkg }} package is installed
  tags: dome9
  become: true
  yum:
    name: "{{ item }}"
    state: present
  register: dome9_yum
  with_items: "{{ dome9_tempfile.path }}"
  when: dome9_get_url is success

- name: Attempting to purge temporary package from the filesystem
  tags: dome9
  file:
    path: "{{ dome9_tempfile.path }}"
    state: absent
  when:
    - dome9_tempfile is success
    - dome9_yum is success

- name: Attempting to overlay dome9 repository configurations
  tags: dome9
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: Dome9.repo.j2, dst: /etc/yum.repos.d/Dome9.repo }
  when: dome9_yum is success

- name: Ensure that the dome9 gpg keys are installed
  tags: dome9
  become: true
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-dome9.com
    state: present
  when: dome9_yum is success

- name: Ensure that the required dome9 packages are installed
  tags: dome9
  become: true
  yum:
    disablerepo: "{{ dome9_disablerepo|join(',') }}"
    enablerepo: "{{ dome9_enablerepo|join(',') }}"
    name: "{{ item }}"
    state: present
  with_items: "{{ dome9_packages }}"
  when:
    - dome9_packages|length > 0
    - dome9_yum is success
...
